"""rehuco-core: shared library for models, .rehu I/O, and sync primitives."""

from .checksum_algorithms import (
    CHECKSUM_ALGORITHMS,
    CHECKSUM_READ_CHUNK_SIZE,
    DEFAULT_CHECKSUM_ALGORITHM,
    ChecksumAlgorithm,
    ChecksumDigest,
)
from .collection_entries import CollectionEntry, collection_entries, collection_records
from .constants import (
    ARCHIVE_EXTENSIONS,
    CHECKSUM_MANIFEST_EXTENSIONS,
    CONTENT_IMAGE_EXTENSIONS,
    EXCLUDED_FILE_PATTERNS,
    IMAGE_EXTENSIONS,
    INFO_REHU_FILENAME,
    REHU_SUFFIX,
    VIDEO_EXTENSIONS,
)
from .learning_path_entries import (
    LearningPathEntry,
    learning_path_records_by_scope,
    learning_path_ref,
    owned_learning_paths,
    visible_learning_paths,
)
from .lock_reasons import LockReason, LockReasonKind
from .migrations import (
    CURRENT_FORMAT_VERSION,
    current_block_version,
    migrate_block_data,
    migrate_rehu_data,
)
from .plugins import (
    BUILTIN_PLUGINS,
    COLLECTION_PLUGIN,
    CORE_FIELD_NAMES,
    CORE_PLUGIN,
    DEFAULT_CURRENT_USERNAME,
    DEFAULT_PLUGIN_REGISTRY,
    DEFAULT_UNKNOWN_USERNAME,
    PUBLIC_USERNAME,
    REFERENCE_IMAGES_FIELD_NAMES,
    REFERENCE_IMAGES_PLUGIN,
    RESOURCE_FIELD_NAMES,
    TUTORIAL_FIELD_NAMES,
    TUTORIAL_PLUGIN,
    USERS_KEY,
    PluginRegistry,
    PluginSpec,
)
from .rehu_content_duration import (
    DEFAULT_DURATION_PROBE,
    DURATION_PROBES,
    DurationProbe,
    DurationProbeError,
    FfprobeDurationProbe,
    MediaInfoDurationProbe,
    content_duration,
)
from .rehu_content_files import content_size_on_disk, enumerate_content_files
from .rehu_content_images import ContentImageEntry, enumerate_content_images
from .rehu_document import (
    AuthorEntry,
    PluginBlock,
    RehuDocument,
    RehuFormatError,
    author_name,
    authors_comma_editable,
)
from .rehu_format import CORE_BLOCK_KEY, FORMAT_VERSION_KEY, RESERVED_KEYS
from .rehu_rename import (
    PartialRenameError,
    RehuRenamer,
    rehu_rename_conflict,
    rename_rehu_resource,
)
from .rehu_screenshots import scan_rehu_screenshot_files
from .storage_traits import readers_must_yield_for_directory_rename
from .tasks import (
    DEFAULT_SHUTDOWN_TIMEOUT,
    DEFAULT_TASK_JOB_REGISTRY,
    FINISHED_JOB_STATES,
    MOVABLE_JOB_STATES,
    RESTORED_UNFINISHED_STATES,
    JobCancelled,
    JobControl,
    JobPaused,
    JobState,
    JobStatus,
    PersistableTaskJob,
    StopRequest,
    TaskJob,
    TaskJobBase,
    TaskJobRegistry,
    TaskQueue,
    TaskQueueItem,
    TaskQueueListener,
)
from .tc_conversion import TcConverter, convert_tc
from .tc_description import TcDescriptionRewriter, rewrite_description_images
from .tc_document import TcDocument, load_tc, tc_to_rehu_data
from .tc_screenshots import ScreenshotRename, TcScreenshotScanner, scan_tc_screenshot_files, scan_tc_screenshots
from .titled_index import INDEX_KEY, TITLE_KEY, titled_index, with_titled_index

__version__ = "0.1.0"

# plain `sorted()` order -- uppercase names, then `__version__`, then the lowercase ones -- so a new
# export has exactly one correct place and no convention to remember (`borco_core.__init__` is the same)
__all__ = [
    "with_titled_index",
    "titled_index",
    "TITLE_KEY",
    "INDEX_KEY",
    "ARCHIVE_EXTENSIONS",
    "AuthorEntry",
    "BUILTIN_PLUGINS",
    "CHECKSUM_ALGORITHMS",
    "CHECKSUM_MANIFEST_EXTENSIONS",
    "CHECKSUM_READ_CHUNK_SIZE",
    "COLLECTION_PLUGIN",
    "CONTENT_IMAGE_EXTENSIONS",
    "CORE_BLOCK_KEY",
    "CORE_FIELD_NAMES",
    "CORE_PLUGIN",
    "CURRENT_FORMAT_VERSION",
    "ChecksumAlgorithm",
    "ChecksumDigest",
    "CollectionEntry",
    "ContentImageEntry",
    "DEFAULT_CHECKSUM_ALGORITHM",
    "DEFAULT_CURRENT_USERNAME",
    "DEFAULT_DURATION_PROBE",
    "DEFAULT_PLUGIN_REGISTRY",
    "DEFAULT_SHUTDOWN_TIMEOUT",
    "DEFAULT_TASK_JOB_REGISTRY",
    "DEFAULT_UNKNOWN_USERNAME",
    "DURATION_PROBES",
    "DurationProbe",
    "DurationProbeError",
    "EXCLUDED_FILE_PATTERNS",
    "FINISHED_JOB_STATES",
    "FORMAT_VERSION_KEY",
    "FfprobeDurationProbe",
    "IMAGE_EXTENSIONS",
    "INFO_REHU_FILENAME",
    "JobCancelled",
    "JobControl",
    "JobPaused",
    "JobState",
    "JobStatus",
    "LearningPathEntry",
    "LockReason",
    "LockReasonKind",
    "MOVABLE_JOB_STATES",
    "MediaInfoDurationProbe",
    "PUBLIC_USERNAME",
    "PartialRenameError",
    "PersistableTaskJob",
    "PluginBlock",
    "PluginRegistry",
    "PluginSpec",
    "REFERENCE_IMAGES_FIELD_NAMES",
    "REFERENCE_IMAGES_PLUGIN",
    "REHU_SUFFIX",
    "RESERVED_KEYS",
    "RESOURCE_FIELD_NAMES",
    "RESTORED_UNFINISHED_STATES",
    "RehuDocument",
    "RehuFormatError",
    "RehuRenamer",
    "ScreenshotRename",
    "StopRequest",
    "TUTORIAL_FIELD_NAMES",
    "TUTORIAL_PLUGIN",
    "TaskJob",
    "TaskJobBase",
    "TaskJobRegistry",
    "TaskQueue",
    "TaskQueueItem",
    "TaskQueueListener",
    "TcConverter",
    "TcDescriptionRewriter",
    "TcDocument",
    "TcScreenshotScanner",
    "USERS_KEY",
    "VIDEO_EXTENSIONS",
    "__version__",
    "author_name",
    "authors_comma_editable",
    "collection_entries",
    "collection_records",
    "content_duration",
    "content_size_on_disk",
    "convert_tc",
    "current_block_version",
    "enumerate_content_files",
    "enumerate_content_images",
    "load_tc",
    "migrate_block_data",
    "migrate_rehu_data",
    "readers_must_yield_for_directory_rename",
    "rehu_rename_conflict",
    "rename_rehu_resource",
    "rewrite_description_images",
    "scan_rehu_screenshot_files",
    "scan_tc_screenshot_files",
    "scan_tc_screenshots",
    "tc_to_rehu_data",
    "learning_path_records_by_scope",
    "learning_path_ref",
    "owned_learning_paths",
    "visible_learning_paths",
]
