"""rehuco-core: shared library for models, .rehu I/O, and sync primitives."""

from .checksum_algorithms import (
    CHECKSUM_ALGORITHMS,
    CHECKSUM_READ_CHUNK_SIZE,
    DEFAULT_CHECKSUM_ALGORITHM,
    ChecksumAlgorithm,
    ChecksumDigest,
)
from .checksum_claim_moves import hand_over_claims
from .checksum_jobs import (
    CHECKSUM_GENERATE_KIND,
    CHECKSUM_SWEEP_KIND,
    CHECKSUM_VERIFY_KIND,
    PRUNE_REASONS,
    ChecksumJob,
    GenerateChecksumsJob,
    SweepChecksumsJob,
    SweepTally,
    VerifyChecksumsJob,
    checksum_report_summary,
    sweep_summary,
)
from .checksum_record import (
    CHECKSUM_FILES_KEY,
    ChecksumEntry,
    ChecksumRecordError,
    ChecksumStatus,
    checksum_entry_name,
    checksum_record_path,
    load_checksum_record,
    new_checksum_record,
    parse_checksum_entry,
    save_checksum_record,
)
from .checksum_seeding import (
    LEGACY_MANIFEST_ALGORITHMS,
    LegacyDrop,
    LegacySeed,
    legacy_manifest_candidates,
    legacy_manifest_for,
    seed_from_legacy_manifest,
)
from .collection_entries import CollectionEntry, collection_entries, collection_records
from .constants import (
    ARCHIVE_EXTENSIONS,
    CHECKSUM_MANIFEST_EXTENSIONS,
    CHECKSUM_RECORD_SUFFIX,
    CONTENT_IMAGE_EXTENSIONS,
    EXCLUDED_FILE_PATTERNS,
    IMAGE_EXTENSIONS,
    INFO_REHU_FILENAME,
    INFO_TC_FILENAME,
    LEGACY_SUFFIX,
    REHU_SUFFIX,
    VIDEO_EXTENSIONS,
)
from .content_reading import DEFAULT_CONTENT_CHUNK_SIZE, read_content_chunks
from .learning_path_entries import (
    LearningPathEntry,
    learning_path_records_by_scope,
    learning_path_ref,
    owned_learning_paths,
    visible_learning_paths,
)
from .lock_reasons import LockReason, LockReasonKind
from .migrations import (
    CURRENT_CHECKSUM_RECORD_VERSION,
    CURRENT_FORMAT_VERSION,
    current_block_version,
    migrate_block_data,
    migrate_checksum_data,
    migrate_rehu_data,
)
from .plugins import (
    BUILTIN_PLUGINS,
    COLLECTION_PLUGIN,
    CORE_FIELD_NAMES,
    CORE_PLUGIN,
    DEFAULT_CURRENT_USERNAME,
    DEFAULT_PLUGIN_REGISTRY,
    DEFAULT_UNKNOWN_USERNAME,
    PUBLIC_USERNAME,
    REFERENCE_IMAGES_FIELD_NAMES,
    REFERENCE_IMAGES_PLUGIN,
    RESOURCE_FIELD_NAMES,
    TUTORIAL_FIELD_NAMES,
    TUTORIAL_PLUGIN,
    USERS_KEY,
    PluginRegistry,
    PluginSpec,
)
from .rehu_catalog import CatalogCheckpoint, CatalogEnumeration, enumerate_catalog_resources
from .rehu_checksums import (
    ChecksumCheckpoint,
    ChecksumProgress,
    ChecksumReport,
    forget_checksums,
    generate_checksums,
    verify_checksums,
)
from .rehu_content_duration import (
    DEFAULT_DURATION_PROBE,
    DURATION_PROBES,
    DurationProbe,
    DurationProbeError,
    FfprobeDurationProbe,
    MediaInfoDurationProbe,
    content_duration,
)
from .rehu_content_files import (
    ContentEnumeration,
    ContentExclusionTier,
    ContentUnreachableError,
    CoveringRecord,
    content_size_on_disk,
    covering_content_records,
    enumerate_content_files,
    excluded_content_names,
)
from .rehu_content_images import ContentImageEntry, enumerate_content_images
from .rehu_document import (
    AuthorEntry,
    PluginBlock,
    RehuDocument,
    RehuFormatError,
    author_name,
    authors_comma_editable,
)
from .rehu_format import CORE_BLOCK_KEY, FORMAT_VERSION_KEY, RESERVED_KEYS
from .rehu_rename import (
    PartialRenameError,
    RehuRenamer,
    rehu_rename_conflict,
    rename_rehu_resource,
)
from .rehu_screenshots import scan_rehu_screenshot_files
from .rename_coordination import (
    DEFAULT_RENAME_COORDINATOR,
    DEFAULT_RENAME_YIELD_TIMEOUT,
    RenameCoordinator,
    RenameYieldTimeout,
    ResourceLocation,
)
from .resource_scoping import (
    DIRECTORY_SCOPED_FILENAMES,
    RECORD_SUFFIXES,
    is_directory_scoped,
    is_directory_scoped_name,
    is_legacy_record_name,
    is_record_name,
    resource_name,
)
from .storage_traits import readers_must_yield_for_directory_rename
from .tasks import (
    DEFAULT_SHUTDOWN_TIMEOUT,
    DEFAULT_TASK_JOB_REGISTRY,
    FINISHED_JOB_STATES,
    MOVABLE_JOB_STATES,
    PROGRESS_UNIT_BYTES,
    PROGRESS_UNIT_RESOURCES,
    RESTORED_UNFINISHED_STATES,
    JobCancelled,
    JobControl,
    JobPaused,
    JobState,
    JobStatus,
    PersistableTaskJob,
    StopRequest,
    TaskJob,
    TaskJobBase,
    TaskJobRegistry,
    TaskQueue,
    TaskQueueItem,
    TaskQueueListener,
)
from .tc_backups_jobs import (
    TC_DISCARD_KIND,
    TC_REVERT_KIND,
    DiscardBackupsJob,
    RevertConversionJob,
    TcBackupsJob,
)
from .tc_conversion import TcConverter, convert_tc, originals_to_back_up
from .tc_conversion_backups import (
    BACKUP_SUFFIX,
    STAGED_SUFFIX,
    ConversionBackups,
    ConversionReverter,
    backup_path,
    conversion_backups,
    discard_conversion_backups,
    is_conversion_backup,
    original_path,
    restore_backup,
    revert_conversion,
)
from .tc_conversion_backups_scan import (
    ConversionBackupsProgress,
    ConversionBackupsScanner,
    ConversionBackupsTreeScan,
    scan_conversion_backups,
)
from .tc_conversion_plan import (
    CLUSTER_MIN_SIZE,
    CLUSTER_WINDOW_SECONDS,
    CONSUMED_TC_KEYS,
    TcConversionPlan,
    TcConversionPlanner,
    TcConversionTreePlan,
    plan_tc_conversion,
)
from .tc_description import TcDescriptionRewriter, rewrite_description_images
from .tc_document import TcDocument, load_tc, tc_to_rehu_data
from .tc_import_job import TC_IMPORT_KIND, TcImportJob
from .tc_screenshots import (
    ScreenshotRename,
    TcScreenshotScanner,
    is_legacy_screenshot,
    scan_tc_screenshot_files,
    scan_tc_screenshots,
)
from .titled_index import INDEX_KEY, TITLE_KEY, titled_index, with_titled_index

__version__ = "0.1.0"

# plain `sorted()` order -- uppercase names, then `__version__`, then the lowercase ones -- so a new
# export has exactly one correct place and no convention to remember (`borco_core.__init__` is the same)
__all__ = [
    "with_titled_index",
    "titled_index",
    "TITLE_KEY",
    "INDEX_KEY",
    "ARCHIVE_EXTENSIONS",
    "AuthorEntry",
    "BACKUP_SUFFIX",
    "BUILTIN_PLUGINS",
    "CHECKSUM_ALGORITHMS",
    "CHECKSUM_FILES_KEY",
    "CHECKSUM_GENERATE_KIND",
    "CHECKSUM_MANIFEST_EXTENSIONS",
    "CHECKSUM_READ_CHUNK_SIZE",
    "CHECKSUM_RECORD_SUFFIX",
    "CHECKSUM_SWEEP_KIND",
    "CHECKSUM_VERIFY_KIND",
    "CLUSTER_MIN_SIZE",
    "CLUSTER_WINDOW_SECONDS",
    "COLLECTION_PLUGIN",
    "CONSUMED_TC_KEYS",
    "CONTENT_IMAGE_EXTENSIONS",
    "CORE_BLOCK_KEY",
    "CORE_FIELD_NAMES",
    "CORE_PLUGIN",
    "CURRENT_CHECKSUM_RECORD_VERSION",
    "CURRENT_FORMAT_VERSION",
    "CatalogCheckpoint",
    "CatalogEnumeration",
    "ChecksumAlgorithm",
    "ChecksumCheckpoint",
    "ChecksumDigest",
    "ChecksumEntry",
    "ChecksumJob",
    "ChecksumProgress",
    "ChecksumRecordError",
    "ChecksumReport",
    "ChecksumStatus",
    "CollectionEntry",
    "ContentEnumeration",
    "ContentExclusionTier",
    "ContentImageEntry",
    "ContentUnreachableError",
    "ConversionBackups",
    "ConversionBackupsProgress",
    "ConversionBackupsScanner",
    "ConversionBackupsTreeScan",
    "ConversionReverter",
    "CoveringRecord",
    "DEFAULT_CHECKSUM_ALGORITHM",
    "DEFAULT_CONTENT_CHUNK_SIZE",
    "DEFAULT_CURRENT_USERNAME",
    "DEFAULT_DURATION_PROBE",
    "DEFAULT_PLUGIN_REGISTRY",
    "DEFAULT_RENAME_COORDINATOR",
    "DEFAULT_RENAME_YIELD_TIMEOUT",
    "DEFAULT_SHUTDOWN_TIMEOUT",
    "DEFAULT_TASK_JOB_REGISTRY",
    "DEFAULT_UNKNOWN_USERNAME",
    "DIRECTORY_SCOPED_FILENAMES",
    "DURATION_PROBES",
    "DiscardBackupsJob",
    "DurationProbe",
    "DurationProbeError",
    "EXCLUDED_FILE_PATTERNS",
    "FINISHED_JOB_STATES",
    "FORMAT_VERSION_KEY",
    "FfprobeDurationProbe",
    "GenerateChecksumsJob",
    "IMAGE_EXTENSIONS",
    "INFO_REHU_FILENAME",
    "INFO_TC_FILENAME",
    "JobCancelled",
    "JobControl",
    "JobPaused",
    "JobState",
    "JobStatus",
    "LEGACY_MANIFEST_ALGORITHMS",
    "LEGACY_SUFFIX",
    "LearningPathEntry",
    "LegacyDrop",
    "LegacySeed",
    "LockReason",
    "LockReasonKind",
    "MOVABLE_JOB_STATES",
    "MediaInfoDurationProbe",
    "PROGRESS_UNIT_BYTES",
    "PROGRESS_UNIT_RESOURCES",
    "PRUNE_REASONS",
    "PUBLIC_USERNAME",
    "PartialRenameError",
    "PersistableTaskJob",
    "PluginBlock",
    "PluginRegistry",
    "PluginSpec",
    "RECORD_SUFFIXES",
    "REFERENCE_IMAGES_FIELD_NAMES",
    "REFERENCE_IMAGES_PLUGIN",
    "REHU_SUFFIX",
    "RESERVED_KEYS",
    "RESOURCE_FIELD_NAMES",
    "RESTORED_UNFINISHED_STATES",
    "RehuDocument",
    "RehuFormatError",
    "RehuRenamer",
    "RenameCoordinator",
    "RenameYieldTimeout",
    "RevertConversionJob",
    "ResourceLocation",
    "STAGED_SUFFIX",
    "ScreenshotRename",
    "StopRequest",
    "SweepChecksumsJob",
    "SweepTally",
    "TC_DISCARD_KIND",
    "TC_IMPORT_KIND",
    "TC_REVERT_KIND",
    "TUTORIAL_FIELD_NAMES",
    "TUTORIAL_PLUGIN",
    "TaskJob",
    "TaskJobBase",
    "TaskJobRegistry",
    "TaskQueue",
    "TaskQueueItem",
    "TaskQueueListener",
    "TcBackupsJob",
    "TcConversionPlan",
    "TcConversionPlanner",
    "TcConversionTreePlan",
    "TcConverter",
    "TcDescriptionRewriter",
    "TcDocument",
    "TcImportJob",
    "TcScreenshotScanner",
    "USERS_KEY",
    "VerifyChecksumsJob",
    "VIDEO_EXTENSIONS",
    "__version__",
    "author_name",
    "authors_comma_editable",
    "backup_path",
    "checksum_entry_name",
    "checksum_record_path",
    "checksum_report_summary",
    "collection_entries",
    "collection_records",
    "content_duration",
    "content_size_on_disk",
    "conversion_backups",
    "convert_tc",
    "covering_content_records",
    "current_block_version",
    "discard_conversion_backups",
    "enumerate_catalog_resources",
    "enumerate_content_files",
    "excluded_content_names",
    "enumerate_content_images",
    "forget_checksums",
    "generate_checksums",
    "hand_over_claims",
    "is_conversion_backup",
    "is_directory_scoped",
    "is_directory_scoped_name",
    "is_legacy_record_name",
    "is_legacy_screenshot",
    "is_record_name",
    "legacy_manifest_candidates",
    "legacy_manifest_for",
    "load_checksum_record",
    "load_tc",
    "migrate_block_data",
    "migrate_checksum_data",
    "migrate_rehu_data",
    "new_checksum_record",
    "original_path",
    "originals_to_back_up",
    "parse_checksum_entry",
    "plan_tc_conversion",
    "read_content_chunks",
    "readers_must_yield_for_directory_rename",
    "rehu_rename_conflict",
    "rename_rehu_resource",
    "resource_name",
    "restore_backup",
    "revert_conversion",
    "rewrite_description_images",
    "scan_conversion_backups",
    "scan_rehu_screenshot_files",
    "scan_tc_screenshot_files",
    "scan_tc_screenshots",
    "save_checksum_record",
    "seed_from_legacy_manifest",
    "sweep_summary",
    "tc_to_rehu_data",
    "verify_checksums",
    "learning_path_records_by_scope",
    "learning_path_ref",
    "owned_learning_paths",
    "visible_learning_paths",
]
