/*
 * launcher.c — in-process Python launcher for rehuco (development mode).
 *
 * Compiled once with VS2022 + CMake. Linked as SUBSYSTEM:WINDOWS so no console
 * window flashes on double-click. Has the app icon in PE resources (ID=1) so
 * Windows uses it for pinned shortcuts and Qt uses it as the default window icon.
 *
 * At runtime this exe:
 *   1. Declares the AUMID (must happen before any window is created)
 *   2. Initialises CPython using the venv Python path baked in by CMake (config.h)
 *      so that pyvenv.cfg is found and the editable install is visible
 *   3. Forwards argv and calls spike.app:main() in-process
 *
 * Because Python runs inside *this* process the QMainWindow's HWND belongs to
 * this exe → taskbar button and pinned shortcut both use this exe's icon.
 */

#define UNICODE
#define _UNICODE
#define WIN32_LEAN_AND_MEAN

#include <windows.h>
#include <shellapi.h> /* CommandLineToArgvW */
#include <shlobj.h>   /* SetCurrentProcessExplicitAppUserModelID */
#include <Python.h>

#include "config.h"   /* VENV_PYTHON_EXECUTABLE — generated by CMake configure_file */

#pragma comment(lib, "shell32.lib")

/* Must match the AUMID in spike/app.py */
static const wchar_t *AUMID = L"Rehuco.Agent.Spike";

/*
 * Entry-point script passed to PyRun_SimpleString.
 * Uses spike.app:main() which is the editable install — changes to .py files
 * are reflected on the next launch with no rebuild needed.
 */
static const char *ENTRY_SCRIPT =
    "import sys\n"
    "from spike.app import main\n"
    "sys.exit(main())\n";

int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                    LPWSTR lpCmdLine, int nShowCmd) {
    (void)hInstance; (void)hPrevInstance; (void)lpCmdLine; (void)nShowCmd;

    /* 1. AUMID — must be first, before QApplication constructs any HWND */
    SetCurrentProcessExplicitAppUserModelID(AUMID);

    /* 2. Verify the venv Python (path baked in by CMake at configure time) */
    if (GetFileAttributesW(VENV_PYTHON_EXECUTABLE) == INVALID_FILE_ATTRIBUTES) {
        MessageBoxW(NULL,
            L"Venv Python not found at the path configured by CMake:\n\n"
            VENV_PYTHON_EXECUTABLE
            L"\n\nRe-run cmake after recreating the venv.",
            L"Rehuco launcher", MB_ICONERROR | MB_OK);
        return 1;
    }

    /* 3. Initialise Python pointing at the venv executable.
     *    Python reads pyvenv.cfg next to that exe and activates the venv,
     *    making the editable install visible via site-packages. */
    PyConfig config;
    PyConfig_InitPythonConfig(&config);

    PyStatus status = PyConfig_SetString(&config, &config.executable, VENV_PYTHON_EXECUTABLE);
    if (PyStatus_Exception(status))
        goto fail;

    /* Forward command-line arguments (file path from Explorer, etc.).
     *
     * PyConfig_SetArgv maps config.argv directly to sys.argv, BUT Python's init
     * consumes argv[0] as the "interpreter name" and shifts the rest down.  So a
     * call with ["launcher.exe", "file.rehu"] yields sys.argv = ["file.rehu"].
     * Prepend an extra copy of argv[0] so Python's shift leaves sys.argv intact:
     *   we pass: ["launcher.exe", "launcher.exe", "file.rehu"]
     *   Python shifts: sys.argv = ["launcher.exe", "file.rehu"]
     */
    int argc;
    wchar_t **argv = CommandLineToArgvW(GetCommandLineW(), &argc);
    if (argv) {
        wchar_t **padded = (wchar_t **)LocalAlloc(LMEM_FIXED, (argc + 1) * sizeof(wchar_t *));
        if (padded) {
            padded[0] = argv[0];
            for (int i = 0; i < argc; i++)
                padded[i + 1] = argv[i];
            status = PyConfig_SetArgv(&config, argc + 1, padded);
            LocalFree(padded);
        } else {
            status = PyConfig_SetArgv(&config, argc, argv);
        }
        LocalFree(argv);
        if (PyStatus_Exception(status))
            goto fail;
    }

    status = Py_InitializeFromConfig(&config);
    if (PyStatus_Exception(status))
        goto fail;

    PyConfig_Clear(&config);

    /* 4. Run the app — editable install means source changes are live */
    PyRun_SimpleString(ENTRY_SCRIPT);
    return Py_FinalizeEx();

fail:
    PyConfig_Clear(&config);
    if (PyStatus_IsError(status))
        MessageBoxA(NULL, status.err_msg, "Rehuco launcher — Python init failed",
                    MB_ICONERROR | MB_OK);
    return 1;
}
