/*
 * launcher.c — in-process Python launcher for rehuco-agent (development mode only).
 *
 * Dev-only tooling: gives a local double-click/registration target with correct Windows
 * app identity (icon, AUMID, taskbar pin) while running against the live editable install.
 * Never built, referenced, or shipped by `make publish` or a Briefcase package build --
 * the real distribution launcher is `rehuco-agent.exe` (the PyPI console-script entry point)
 * or, later, Briefcase's own generated launcher (§16.8).
 *
 * Compiled once with VS2022 + CMake. Linked as SUBSYSTEM:WINDOWS so no console window
 * flashes on double-click. Has the app icon in PE resources (ID=1) so Windows uses it for
 * pinned shortcuts and Qt uses it as the default window icon.
 *
 * At runtime this exe:
 *   1. Declares the AUMID (must happen before any window is created)
 *   2. Initialises CPython using the workspace venv Python path baked in by CMake (config.h)
 *   3. Makes the editable install visible via an explicit site.addsitedir() on the venv's
 *      site-packages (see ENTRY_SCRIPT_FMT's comment -- venv auto-activation was not reliable
 *      here) and forwards argv, then calls rehuco_agent.__main__:main() in-process -- so
 *      double-click, --register, and --unregister all behave like the real packaged CLI
 *
 * Because Python runs inside *this* process the QMainWindow's HWND belongs to this exe ->
 * taskbar button and pinned shortcut both use this exe's icon/identity.
 */

#define UNICODE
#define _UNICODE
#define WIN32_LEAN_AND_MEAN

#include <windows.h>
#include <shellapi.h> /* CommandLineToArgvW */
#include <shlobj.h>   /* SetCurrentProcessExplicitAppUserModelID */
#include <Python.h>

#include "config.h"   /* VENV_PYTHON_EXECUTABLE — generated by CMake configure_file */

#pragma comment(lib, "shell32.lib")

/* Must match win_registration.AUMID in rehuco_agent/platforms/windows/win_registration.py */
static const wchar_t *AUMID = L"borco.rehuco.agent";

/*
 * Entry-point script passed to PyRun_SimpleString, built at runtime via ENTRY_SCRIPT_FMT.
 *
 * CPython's own pyvenv.cfg auto-detection did not reliably activate the workspace venv when
 * embedding via Py_InitializeFromConfig on this CPython 3.14 build (confirmed environment-
 * level, not project-specific: the pre-existing win-file-assoc-identity spike's own exe now
 * fails identically). Working around it directly: call site.addsitedir() on the venv's
 * site-packages explicitly, which processes the editable-install .pth files rather than
 * relying on venv auto-activation. Uses rehuco_agent.__main__:main() (not app:run() directly)
 * via that editable install, so --register/--unregister/paths all work exactly like the real
 * packaged rehuco-agent.exe CLI does -- __main__.main() registers whatever exe is actually
 * running (sys.argv[0]), so this trampoline registers itself, not the packaged entry point.
 * Changes to .py files are reflected on the next launch with no rebuild needed.
 */
static const char *ENTRY_SCRIPT_FMT =
    "import sys, site\n"
    "site.addsitedir(r'%s')\n"
    "from rehuco_agent.__main__ import main\n"
    "sys.exit(main())\n";

int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                    LPWSTR lpCmdLine, int nShowCmd) {
    (void)hInstance; (void)hPrevInstance; (void)lpCmdLine; (void)nShowCmd;

    /* 1. AUMID — must be first, before QApplication constructs any HWND */
    SetCurrentProcessExplicitAppUserModelID(AUMID);

    /* 2. Verify the workspace venv Python (path baked in by CMake at configure time) */
    if (GetFileAttributesW(VENV_PYTHON_EXECUTABLE) == INVALID_FILE_ATTRIBUTES) {
        MessageBoxW(NULL,
            L"Workspace venv Python not found at the path configured by CMake:\n\n"
            VENV_PYTHON_EXECUTABLE
            L"\n\nRe-run cmake after recreating the venv.",
            L"rehuco-agent dev launcher", MB_ICONERROR | MB_OK);
        return 1;
    }

    /* 3. Initialise Python. config.executable is set so sys.executable reports the venv
     *    python correctly; actual package visibility comes from the explicit
     *    site.addsitedir() call in the entry script below (see its comment for why). */
    PyConfig config;
    PyConfig_InitPythonConfig(&config);

    PyStatus status = PyConfig_SetString(&config, &config.executable, VENV_PYTHON_EXECUTABLE);
    if (PyStatus_Exception(status))
        goto fail;

    /* Forward command-line arguments (file path from Explorer, etc.).
     *
     * PyConfig_SetArgv maps config.argv directly to sys.argv, BUT Python's init
     * consumes argv[0] as the "interpreter name" and shifts the rest down.  So a
     * call with ["launcher.exe", "file.rehu"] yields sys.argv = ["file.rehu"].
     * Prepend an extra copy of argv[0] so Python's shift leaves sys.argv intact:
     *   we pass: ["launcher.exe", "launcher.exe", "file.rehu"]
     *   Python shifts: sys.argv = ["launcher.exe", "file.rehu"]
     */
    int argc;
    wchar_t **argv = CommandLineToArgvW(GetCommandLineW(), &argc);
    if (argv) {
        wchar_t **padded = (wchar_t **)LocalAlloc(LMEM_FIXED, (argc + 1) * sizeof(wchar_t *));
        if (padded) {
            padded[0] = argv[0];
            for (int i = 0; i < argc; i++)
                padded[i + 1] = argv[i];
            status = PyConfig_SetArgv(&config, argc + 1, padded);
            LocalFree(padded);
        } else {
            status = PyConfig_SetArgv(&config, argc, argv);
        }
        LocalFree(argv);
        if (PyStatus_Exception(status))
            goto fail;
    }

    status = Py_InitializeFromConfig(&config);
    if (PyStatus_Exception(status))
        goto fail;

    PyConfig_Clear(&config);

    /* 4. Run the app — editable install means source changes are live */
    char entry_script[1024];
    _snprintf_s(entry_script, sizeof(entry_script), _TRUNCATE, ENTRY_SCRIPT_FMT, VENV_SITE_PACKAGES_UTF8);
    PyRun_SimpleString(entry_script);
    return Py_FinalizeEx();

fail:
    PyConfig_Clear(&config);
    if (PyStatus_IsError(status))
        MessageBoxA(NULL, status.err_msg, "rehuco-agent dev launcher — Python init failed",
                    MB_ICONERROR | MB_OK);
    return 1;
}
